package com.balicamp.model.report;

// Generated Jan 3, 2013 4:38:55 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.balicamp.model.admin.BaseAdminModel;

/**
 * MMxReportColumParam generated by hbm2java
 * @version $Id: $
 */
@Entity
@Table(name = "m_mx_report_colum_param")
public class ReportColumModel extends BaseAdminModel {

	private Long idColum;
	private ReportModel report;
	private String fieldName;
	private String fieldString;
	private String tipeData;
	private boolean isSum;
	private Long length;
	private String margin;
	private Long sequence;
	private boolean isRowCount;
	private String condition;
	private String keyDataFormater;

	public ReportColumModel() {
	}

	public ReportColumModel(Long idColum, ReportModel report, String fieldName, String fieldString, String tipeData,
			boolean isSum, Long length, String margin, Long sequence, boolean isRowCount) {
		this.idColum = idColum;
		this.report = report;
		this.fieldName = fieldName;
		this.fieldString = fieldString;
		this.tipeData = tipeData;
		this.isSum = isSum;
		this.length = length;
		this.margin = margin;
		this.sequence = sequence;
		this.isRowCount = isRowCount;
	}

	public ReportColumModel(Long idColum, ReportModel report, String fieldName, String fieldString, String tipeData,
			boolean isSum, Long length, String margin, Long sequence, boolean isRowCount, String condition) {
		this.idColum = idColum;
		this.report = report;
		this.fieldName = fieldName;
		this.fieldString = fieldString;
		this.tipeData = tipeData;
		this.isSum = isSum;
		this.length = length;
		this.margin = margin;
		this.sequence = sequence;
		this.isRowCount = isRowCount;
		this.condition = condition;
	}

	@Id
	@Column(name = "id_colum", unique = true, nullable = false)
	public Long getIdColum() {
		return this.idColum;
	}

	public void setIdColum(Long idColum) {
		this.idColum = idColum;
	}
	@Column(name = "field_name", nullable = false, length = 25)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "field_string", nullable = false, length = 25)
	public String getFieldString() {
		return this.fieldString;
	}

	public void setFieldString(String fieldString) {
		this.fieldString = fieldString;
	}

	@Column(name = "tipe_data", nullable = false, length = 8)
	public String getTipeData() {
		return this.tipeData;
	}

	public void setTipeData(String tipeData) {
		this.tipeData = tipeData;
	}

	@Column(name = "is_sum", nullable = false)
	public boolean isSum() {
		return this.isSum;
	}

	public void setSum(boolean isSum) {
		this.isSum = isSum;
	}

	@Column(name = "length", nullable = false)
	public Long getLength() {
		return this.length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	@Column(name = "margin", nullable = false, length = 8)
	public String getMargin() {
		return this.margin;
	}

	public void setMargin(String margin) {
		this.margin = margin;
	}

	@Column(name = "sequence", nullable = false)
	public Long getSequence() {
		return this.sequence;
	}

	public void setSequence(Long sequence) {
		this.sequence = sequence;
	}

	@Column(name = "is_row_count", nullable = false)
	public boolean isRowCount() {
		return this.isRowCount;
	}

	public void setRowCount(boolean isRowCount) {
		this.isRowCount = isRowCount;
	}

	@Column(name = "condition", length = 150)
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_report", nullable = false)
	public ReportModel getReport() {
		return report;
	}
	
	public void setReport(ReportModel report) {
		this.report = report;
	}
	
	@Column(name = "key_data_formater", length = 255)
	public String getKeyDataFormater() {
		return keyDataFormater;
	}
	public void setKeyDataFormater(String keyDataFormater) {
		this.keyDataFormater = keyDataFormater;
	}

	@Override
	@Transient
	public String getPKey() {
		return String.valueOf(getIdColum());
	}
}
