package ws.billpayment.h2h.bankmandiri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-21T14:53:43.906+07:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "BillPaymentService", 
                  wsdlLocation = "BillPaymentService.wsdl",
                  targetNamespace = "bankmandiri.h2h.billpayment.ws") 
public class BillPaymentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("bankmandiri.h2h.billpayment.ws", "BillPaymentService");
    public final static QName BillPaymentServiceSoap = new QName("bankmandiri.h2h.billpayment.ws", "BillPaymentServiceSoap");
    static {
        URL url = BillPaymentService.class.getResource("BillPaymentService.wsdl");
        if (url == null) {
            url = BillPaymentService.class.getClassLoader().getResource("BillPaymentService.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(BillPaymentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "BillPaymentService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BillPaymentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillPaymentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillPaymentService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns BillPaymentServiceSoap
     */
    @WebEndpoint(name = "BillPaymentServiceSoap")
    public BillPaymentServiceSoap getBillPaymentServiceSoap() {
        return super.getPort(BillPaymentServiceSoap, BillPaymentServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillPaymentServiceSoap
     */
    @WebEndpoint(name = "BillPaymentServiceSoap")
    public BillPaymentServiceSoap getBillPaymentServiceSoap(WebServiceFeature... features) {
        return super.getPort(BillPaymentServiceSoap, BillPaymentServiceSoap.class, features);
    }

}
