package ws.billpayment.h2h.bankmandiri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-21T14:53:43.890+07:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "bankmandiri.h2h.billpayment.ws", name = "BillPaymentServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BillPaymentServiceSoap {

    @WebResult(name = "echoTestResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "echoTest", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.EchoTest")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/echoTest")
    @ResponseWrapper(localName = "echoTestResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.EchoTestResponse")
    public java.lang.String echoTest(
        @WebParam(name = "tx", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        java.lang.String tx
    );

    @WebResult(name = "inquiryResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "inquiry", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.Inquiry")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/inquiry")
    @ResponseWrapper(localName = "inquiryResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.InquiryResponse")
    public ws.billpayment.h2h.bankmandiri.InquiryResponse2 inquiry(
        @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        ws.billpayment.h2h.bankmandiri.InquiryRequest request
    );

    @WebResult(name = "reverseResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "reverse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.Reverse")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.ReverseResponse")
    public ws.billpayment.h2h.bankmandiri.ReversalResponse reverse(
        @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        ws.billpayment.h2h.bankmandiri.ReversalRequest request
    );

    @WebResult(name = "paymentResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "payment", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.Payment")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bankmandiri.PaymentResponse")
    public ws.billpayment.h2h.bankmandiri.PaymentResponse2 payment(
        @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        ws.billpayment.h2h.bankmandiri.PaymentRequest request
    );
}
