
package ws.billpayment.h2h.bankmandiri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-05-21T14:53:43.828+07:00
 * Generated source version: 2.7.5
 * 
 */
public final class BillPaymentServiceSoap_BillPaymentServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("bankmandiri.h2h.billpayment.ws", "BillPaymentService");

    private BillPaymentServiceSoap_BillPaymentServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BillPaymentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BillPaymentService ss = new BillPaymentService(wsdlURL, SERVICE_NAME);
        BillPaymentServiceSoap port = ss.getBillPaymentServiceSoap();  
        
        {
        System.out.println("Invoking echoTest...");
        java.lang.String _echoTest_tx = "";
        java.lang.String _echoTest__return = port.echoTest(_echoTest_tx);
        System.out.println("echoTest.result=" + _echoTest__return);


        }
        {
        System.out.println("Invoking inquiry...");
        ws.billpayment.h2h.bankmandiri.InquiryRequest _inquiry_request = null;
        ws.billpayment.h2h.bankmandiri.InquiryResponse2 _inquiry__return = port.inquiry(_inquiry_request);
        System.out.println("inquiry.result=" + _inquiry__return);


        }
        {
        System.out.println("Invoking reverse...");
        ws.billpayment.h2h.bankmandiri.ReversalRequest _reverse_request = null;
        ws.billpayment.h2h.bankmandiri.ReversalResponse _reverse__return = port.reverse(_reverse_request);
        System.out.println("reverse.result=" + _reverse__return);


        }
        {
        System.out.println("Invoking payment...");
        ws.billpayment.h2h.bankmandiri.PaymentRequest _payment_request = null;
        ws.billpayment.h2h.bankmandiri.PaymentResponse2 _payment__return = port.payment(_payment_request);
        System.out.println("payment.result=" + _payment__return);


        }

        System.exit(0);
    }

}
