package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Conditionings generated by hbm2java
 * @version $Id: Conditionings.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "conditionings", uniqueConstraints = @UniqueConstraint(columnNames = { "route_id", "path" }))
public class Conditionings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int id;
	private Routes routes;
	private String path;
	private String data;

	public Conditionings() {
	}

	public Conditionings(int id, Routes routes, String path, String data) {
		this.id = id;
		this.routes = routes;
		this.path = path;
		this.data = data;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "route_id", nullable = false)
	public Routes getRoutes() {
		return this.routes;
	}

	public void setRoutes(Routes routes) {
		this.routes = routes;
	}

	@Column(name = "path", nullable = false, length = 100)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "data", nullable = false)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
