package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mappings generated by hbm2java
 * @version $Id: Mappings.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "mappings", uniqueConstraints = @UniqueConstraint(columnNames = { "code", "endpoint_id" }))
public class Mappings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int id;
	private Endpoints endpoints;
	private Packagers packagers;
	private String code;
	private String description;
	private Set<Routes> routesesForLastInvocationId = new HashSet<Routes>(0);
	private Set<Routes> routesesForNextInvocationId = new HashSet<Routes>(0);
	private Set<Timeouts> timeoutses = new HashSet<Timeouts>(0);
	private Set<MappingDetails> mappingDetailses = new HashSet<MappingDetails>(0);

	public Mappings() {
	}

	public Mappings(int id, Endpoints endpoints, String code, String description) {
		this.id = id;
		this.endpoints = endpoints;
		this.code = code;
		this.description = description;
	}

	public Mappings(int id, Endpoints endpoints, Packagers packagers, String code, String description,
			Set<Routes> routesesForLastInvocationId, Set<Routes> routesesForNextInvocationId, Set<Timeouts> timeoutses,
			Set<MappingDetails> mappingDetailses) {
		this.id = id;
		this.endpoints = endpoints;
		this.packagers = packagers;
		this.code = code;
		this.description = description;
		this.routesesForLastInvocationId = routesesForLastInvocationId;
		this.routesesForNextInvocationId = routesesForNextInvocationId;
		this.timeoutses = timeoutses;
		this.mappingDetailses = mappingDetailses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "endpoint_id", nullable = false)
	public Endpoints getEndpoints() {
		return this.endpoints;
	}

	public void setEndpoints(Endpoints endpoints) {
		this.endpoints = endpoints;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packager_id")
	public Packagers getPackagers() {
		return this.packagers;
	}

	public void setPackagers(Packagers packagers) {
		this.packagers = packagers;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mappingsByLastInvocationId")
	public Set<Routes> getRoutesesForLastInvocationId() {
		return this.routesesForLastInvocationId;
	}

	public void setRoutesesForLastInvocationId(Set<Routes> routesesForLastInvocationId) {
		this.routesesForLastInvocationId = routesesForLastInvocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mappingsByNextInvocationId")
	public Set<Routes> getRoutesesForNextInvocationId() {
		return this.routesesForNextInvocationId;
	}

	public void setRoutesesForNextInvocationId(Set<Routes> routesesForNextInvocationId) {
		this.routesesForNextInvocationId = routesesForNextInvocationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mappings")
	public Set<Timeouts> getTimeoutses() {
		return this.timeoutses;
	}

	public void setTimeoutses(Set<Timeouts> timeoutses) {
		this.timeoutses = timeoutses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mappings")
	public Set<MappingDetails> getMappingDetailses() {
		return this.mappingDetailses;
	}

	public void setMappingDetailses(Set<MappingDetails> mappingDetailses) {
		this.mappingDetailses = mappingDetailses;
	}

}
