package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.balicamp.model.admin.BaseAdminModel;

/**
 * MessageLogs generated by hbm2java
 * @version $Id: MessageLogs.java 175 2013-01-09 09:22:25Z bagus.sugitayasa $
 */
@Entity
@Table(name = "message_logs_housekeeping")
public class MessageLogsHousekeeping extends BaseAdminModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private MessageLogsId id;

	private TransactionLogs transactionLogs;

	public MessageLogsHousekeeping() {
	}

	public MessageLogsHousekeeping(MessageLogsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "transactionId", column = @Column(name = "transaction_id",
			nullable = false, length = 50)), @AttributeOverride(name = "conversionTime", column = @Column(
			name = "conversion_time", nullable = false, length = 29)), @AttributeOverride(name = "endpointCode",
			column = @Column(name = "endpoint_code", nullable = false, length = 10)), @AttributeOverride(
			name = "mappingCode", column = @Column(name = "mapping_code", nullable = false, length = 50)), @AttributeOverride(
			name = "isRequest", column = @Column(name = "is_request", nullable = false)), @AttributeOverride(
			name = "raw", column = @Column(name = "raw", nullable = false, length = 8192)) })
	public MessageLogsId getId() {
		return this.id;
	}

	public void setId(MessageLogsId id) {
		this.id = id;
	}

	@Transient
	public TransactionLogs getTransLogs() {
		return transactionLogs;
	}

	public void setTransLogs(TransactionLogs transLogs) {
		this.transactionLogs = transLogs;
	}

	@Override
	@Transient
	public String getPKey() {
		// FIXME : cek lagi key yang berkaitan
		return null;
	}

}
