package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Timeouts generated by hbm2java
 * @version $Id: Timeouts.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "timeouts", uniqueConstraints = @UniqueConstraint(columnNames = "invocation_id"))
public class Timeouts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private TimeoutsId id;
	private Mappings mappings;

	public Timeouts() {
	}

	public Timeouts(TimeoutsId id, Mappings mappings) {
		this.id = id;
		this.mappings = mappings;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "invocationId", column = @Column(name = "invocation_id",
			unique = true, nullable = false)), @AttributeOverride(name = "length", column = @Column(name = "length",
			nullable = false)) })
	public TimeoutsId getId() {
		return this.id;
	}

	public void setId(TimeoutsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invocation_id", unique = true, nullable = false, insertable = false, updatable = false)
	public Mappings getMappings() {
		return this.mappings;
	}

	public void setMappings(Mappings mappings) {
		this.mappings = mappings;
	}

}
