
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package id.co.sigma.mx.channel.endpoint;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2017-10-03T09:38:16.328+07:00
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "PaymentManagerControllerService",
                      portName = "PaymentManagerControllerPort",
                      targetNamespace = "urn:PaymentManagerControllerwsdl",
                      wsdlLocation = "classpath:wsdl/pap.wsdl",
                      endpointInterface = "id.co.sigma.mx.channel.endpoint.PaymentManagerControllerPortType")
                      
public class PaymentManagerControllerPortTypeImpl implements PaymentManagerControllerPortType {

    private static final Logger LOG = Logger.getLogger(PaymentManagerControllerPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see paymentmanagercontrollerwsdl.PaymentManagerControllerPortType#reversal(paymentmanagercontrollerwsdl.ReversalRequest  req )*
     */
    public id.co.sigma.mx.channel.endpoint.ReversalResult reversal(id.co.sigma.mx.channel.endpoint.ReversalRequest req) { 
        LOG.info("Executing operation reversal");
        System.out.println(req);
        try {
        	id.co.sigma.mx.channel.endpoint.ReversalResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see paymentmanagercontrollerwsdl.PaymentManagerControllerPortType#payment(paymentmanagercontrollerwsdl.PaymentRequest  req )*
     */
    public id.co.sigma.mx.channel.endpoint.PaymentResult payment(id.co.sigma.mx.channel.endpoint.PaymentRequest req) { 
        LOG.info("Executing operation payment");
        System.out.println(req);
        try {
        	id.co.sigma.mx.channel.endpoint.PaymentResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see paymentmanagercontrollerwsdl.PaymentManagerControllerPortType#inquiry(paymentmanagercontrollerwsdl.InquiryRequest  req )*
     */
    public id.co.sigma.mx.channel.endpoint.InquiryResult inquiry(id.co.sigma.mx.channel.endpoint.InquiryRequest req) { 
        LOG.info("Executing operation inquiry");
        System.out.println(req);
        try {
        	id.co.sigma.mx.channel.endpoint.InquiryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
