package id.co.sigma.mx.channel.ws.wsdl.bni.sya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2015-08-28T13:17:32.484+07:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "bni.h2h.billpayment.ws", name = "BillPaymentServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BillPaymentServiceSoap {

    @WebResult(name = "echoTestResult", targetNamespace = "bni.h2h.billpayment.ws")
    @RequestWrapper(localName = "echoTest", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.EchoTest")
    @WebMethod(action = "bni.h2h.billpayment.ws/echoTest")
    @ResponseWrapper(localName = "echoTestResponse", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.EchoTestResponse")
    public java.lang.String echoTest(
        @WebParam(name = "tx", targetNamespace = "bni.h2h.billpayment.ws")
        java.lang.String tx
    );

    @WebResult(name = "paymentResult", targetNamespace = "bni.h2h.billpayment.ws")
    @RequestWrapper(localName = "payment", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.Payment")
    @WebMethod(action = "bni.h2h.billpayment.ws/payment")
    @ResponseWrapper(localName = "paymentResponse2", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.PaymentResponse2")
    public PaymentResponse payment(
        @WebParam(name = "request", targetNamespace = "bni.h2h.billpayment.ws")
        PaymentRequest request
    );

    @WebResult(name = "reverseResult", targetNamespace = "bni.h2h.billpayment.ws")
    @RequestWrapper(localName = "reverse", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.Reverse")
    @WebMethod(action = "bni.h2h.billpayment.ws/reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.ReverseResponse")
    public ReversalResponse reverse(
        @WebParam(name = "request", targetNamespace = "bni.h2h.billpayment.ws")
        ReversalRequest request
    );

    @WebResult(name = "inquiryResult", targetNamespace = "bni.h2h.billpayment.ws")
    @RequestWrapper(localName = "inquiry", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.Inquiry")
    @WebMethod(action = "bni.h2h.billpayment.ws/inquiry")
    @ResponseWrapper(localName = "inquiryResponse2", targetNamespace = "bni.h2h.billpayment.ws", className = "ws.billpayment.h2h.bni.InquiryResponse2")
    public InquiryResponse inquiry(
        @WebParam(name = "request", targetNamespace = "bni.h2h.billpayment.ws")
       InquiryRequest request
    );
}
