package com.balicamp.model.report;

// Generated Jan 3, 2013 4:38:55 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.OrderBy;
import com.balicamp.model.admin.BaseAdminModel;

/**
 * MMxReport generated by hbm2java
 * @version $Id: $
 */
@Entity
@Table(name = "m_mx_report")
public class ReportModel extends BaseAdminModel implements Serializable{

	private Long id;
	private String namaReport;
	private String kodeReport;
	private String rc;
	private String kodeTransaksi;
	private String filePrefixName;
	private String resKodeTransaksi;
	private String resRcChannel;
	private String filter;

	private boolean  aktif;

	private String tipe;
	private Long parentGeneric;


	private List<ReportColumModel> colums = new ArrayList<ReportColumModel>();

	public ReportModel() {
	}

	public ReportModel(Long id) {
		this.id = id;
	}

/*	public ReportModel(Long id, String namaReport, String kodeReport,Set<ReportColumModel> columns) {
		this.id = id;
		this.namaReport = namaReport;
		this.colums= columns;
		this.kodeReport = kodeReport;
	}*/

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "kode_report", length = 10,nullable = false)
	public String getKodeReport() {
		return kodeReport;
	}

	public void setKodeReport(String kodeReport) {
		this.kodeReport = kodeReport;
	}

	@Column(name = "nama_report", length = 25,nullable = false)
	public String getNamaReport() {
		return this.namaReport;
	}

	public void setNamaReport(String namaReport) {
		this.namaReport = namaReport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "report" )
	@OrderBy(clause = "sequence asc" )
	public List<ReportColumModel> getColums() {
		return colums;
	}

	public void setColums(List<ReportColumModel> colums) {
		this.colums = colums;
	}


	@Column(name = "rc_channel", length = 25)
	public String getRc() {
		return rc;
	}

	public void setRc(String rc) {
		this.rc = rc;
	}

	@Column(name = "kode_transaksi", length = 25)
	public String getKodeTransaksi() {
		return kodeTransaksi;
	}

	public void setKodeTransaksi(String kodeTransaksi) {
		this.kodeTransaksi = kodeTransaksi;
	}

	@Column(name = "file_prefix_name", length = 100, nullable=false )
	public String getFilePrefixName() {
		return filePrefixName;
	}

	public void setFilePrefixName(String filePrefixName) {
		this.filePrefixName = filePrefixName;
	}

	@Override
	@Transient
	public String getPKey() {
		return String.valueOf(getId());
	}

	@Column(name = "rest_kode_transaksi", length = 5, nullable=false )
	public String getResKodeTransaksi() {
		return resKodeTransaksi;
	}

	public void setResKodeTransaksi(String resKodeTransaksi) {
		this.resKodeTransaksi = resKodeTransaksi;
	}

	@Column(name = "rest_rc_channel", length = 5, nullable=false )
	public String getResRcChannel() {
		return resRcChannel;
	}

	public void setResRcChannel(String resRcChannel) {
		this.resRcChannel = resRcChannel;
	}

	@Column(name = "aktif", nullable=false )
	public boolean isAktif() {
		return aktif;
	}

	public void setAktif(boolean aktif) {
		this.aktif = aktif;
	}

	@Column(name = "type", length = 25)
	public String getTipe() {
		return tipe;
	}


	public void setTipe(String tipe) {
		this.tipe = tipe;
	}

	@Column(name = "parent_generic")
	public Long getParentGeneric() {
		return parentGeneric;
	}

	public void setParentGeneric(Long parentGeneric) {
		this.parentGeneric = parentGeneric;
	}

	@Column(name = "filter", nullable=false )
	public String getFilter() {
		return filter;
	}

	public void setFilter(String filter) {
		this.filter = filter;
	}


}
