package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RcMappings generated by hbm2java
 * @version $Id: RcMappings.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "rc_mappings", uniqueConstraints = @UniqueConstraint(columnNames = { "source_rc_id", "target_rc_id" }))
public class RcMappings implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private RcMappingsId id;
	private EndpointRcs endpointRcsBySourceRcId;
	private EndpointRcs endpointRcsByTargetRcId;

	public RcMappings() {
	}

	public RcMappings(RcMappingsId id, EndpointRcs endpointRcsBySourceRcId, EndpointRcs endpointRcsByTargetRcId) {
		this.id = id;
		this.endpointRcsBySourceRcId = endpointRcsBySourceRcId;
		this.endpointRcsByTargetRcId = endpointRcsByTargetRcId;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "sourceRcId", column = @Column(name = "source_rc_id",
			nullable = false)), @AttributeOverride(name = "targetRcId", column = @Column(name = "target_rc_id",
			nullable = false)) })
	public RcMappingsId getId() {
		return this.id;
	}

	public void setId(RcMappingsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_rc_id", nullable = false, insertable = false, updatable = false)
	public EndpointRcs getEndpointRcsBySourceRcId() {
		return this.endpointRcsBySourceRcId;
	}

	public void setEndpointRcsBySourceRcId(EndpointRcs endpointRcsBySourceRcId) {
		this.endpointRcsBySourceRcId = endpointRcsBySourceRcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "target_rc_id", nullable = false, insertable = false, updatable = false)
	public EndpointRcs getEndpointRcsByTargetRcId() {
		return this.endpointRcsByTargetRcId;
	}

	public void setEndpointRcsByTargetRcId(EndpointRcs endpointRcsByTargetRcId) {
		this.endpointRcsByTargetRcId = endpointRcsByTargetRcId;
	}

}
