package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TimeoutsId generated by hbm2java
 * @version $Id: TimeoutsId.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Embeddable
public class TimeoutsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int invocationId;
	private int length;

	public TimeoutsId() {
	}

	public TimeoutsId(int invocationId, int length) {
		this.invocationId = invocationId;
		this.length = length;
	}

	@Column(name = "invocation_id", unique = true, nullable = false)
	public int getInvocationId() {
		return this.invocationId;
	}

	public void setInvocationId(int invocationId) {
		this.invocationId = invocationId;
	}

	@Column(name = "length", nullable = false)
	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimeoutsId))
			return false;
		TimeoutsId castOther = (TimeoutsId) other;

		return (this.getInvocationId() == castOther.getInvocationId()) && (this.getLength() == castOther.getLength());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInvocationId();
		result = 37 * result + this.getLength();
		return result;
	}

}
