package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionLogsId generated by hbm2java
 * @version $Id: TransactionLogsId.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Embeddable
public class TransactionLogsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String transactionId;
	private Date transactionTime;
	private String transactionCode;
	private String mxRc;
	private String channelCode;
	private String channelRc;
	private String retrievalKey;
	private String type;
	private String raw;

	public TransactionLogsId() {
	}

	public TransactionLogsId(String transactionId, Date transactionTime, String transactionCode, String mxRc,
			String channelCode, String channelRc, String retrievalKey, String type, String raw) {
		this.transactionId = transactionId;
		this.transactionTime = transactionTime;
		this.transactionCode = transactionCode;
		this.mxRc = mxRc;
		this.channelCode = channelCode;
		this.channelRc = channelRc;
		this.retrievalKey = retrievalKey;
		this.type = type;
		this.raw = raw;
	}

	@Column(name = "transaction_id", nullable = false, length = 50)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "transaction_time", nullable = false, length = 29)
	public Date getTransactionTime() {
		return this.transactionTime;
	}

	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	@Column(name = "transaction_code", nullable = false, length = 50)
	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	@Column(name = "mx_rc", nullable = false, length = 10)
	public String getMxRc() {
		return this.mxRc;
	}

	public void setMxRc(String mxRc) {
		this.mxRc = mxRc;
	}

	@Column(name = "channel_code", nullable = false, length = 10)
	public String getChannelCode() {
		return this.channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	@Column(name = "channel_rc", nullable = false, length = 10)
	public String getChannelRc() {
		return this.channelRc;
	}

	public void setChannelRc(String channelRc) {
		this.channelRc = channelRc;
	}

	@Column(name = "retrieval_key", nullable = false, length = 100)
	public String getRetrievalKey() {
		return this.retrievalKey;
	}

	public void setRetrievalKey(String retrievalKey) {
		this.retrievalKey = retrievalKey;
	}

	@Column(name = "type", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "raw", nullable = false, length = 24576)
	public String getRaw() {
		return this.raw;
	}

	public void setRaw(String raw) {
		this.raw = raw;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionLogsId))
			return false;
		TransactionLogsId castOther = (TransactionLogsId) other;

		return ((this.getTransactionId() == castOther.getTransactionId()) || (this.getTransactionId() != null
				&& castOther.getTransactionId() != null && this.getTransactionId().equals(castOther.getTransactionId())))
				&& ((this.getTransactionTime() == castOther.getTransactionTime()) || (this.getTransactionTime() != null
						&& castOther.getTransactionTime() != null && this.getTransactionTime().equals(
						castOther.getTransactionTime())))
				&& ((this.getTransactionCode() == castOther.getTransactionCode()) || (this.getTransactionCode() != null
						&& castOther.getTransactionCode() != null && this.getTransactionCode().equals(
						castOther.getTransactionCode())))
				&& ((this.getMxRc() == castOther.getMxRc()) || (this.getMxRc() != null && castOther.getMxRc() != null && this
						.getMxRc().equals(castOther.getMxRc())))
				&& ((this.getChannelCode() == castOther.getChannelCode()) || (this.getChannelCode() != null
						&& castOther.getChannelCode() != null && this.getChannelCode().equals(
						castOther.getChannelCode())))
				&& ((this.getChannelRc() == castOther.getChannelRc()) || (this.getChannelRc() != null
						&& castOther.getChannelRc() != null && this.getChannelRc().equals(castOther.getChannelRc())))
				&& ((this.getRetrievalKey() == castOther.getRetrievalKey()) || (this.getRetrievalKey() != null
						&& castOther.getRetrievalKey() != null && this.getRetrievalKey().equals(
						castOther.getRetrievalKey())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this
						.getType().equals(castOther.getType())))
				&& ((this.getRaw() == castOther.getRaw()) || (this.getRaw() != null && castOther.getRaw() != null && this
						.getRaw().equals(castOther.getRaw())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTransactionId() == null ? 0 : this.getTransactionId().hashCode());
		result = 37 * result + (getTransactionTime() == null ? 0 : this.getTransactionTime().hashCode());
		result = 37 * result + (getTransactionCode() == null ? 0 : this.getTransactionCode().hashCode());
		result = 37 * result + (getMxRc() == null ? 0 : this.getMxRc().hashCode());
		result = 37 * result + (getChannelCode() == null ? 0 : this.getChannelCode().hashCode());
		result = 37 * result + (getChannelRc() == null ? 0 : this.getChannelRc().hashCode());
		result = 37 * result + (getRetrievalKey() == null ? 0 : this.getRetrievalKey().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getRaw() == null ? 0 : this.getRaw().hashCode());
		return result;
	}

}
