package id.co.sigma.mx.channel.ws.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.ws.rs.Path;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-07T17:11:13.130+07:00
 * Generated source version: 2.7.4
 * 
 */
@Path("/channel")
@WebService(targetNamespace = "bankmandiri.h2h.billpayment.ws", name = "BillPaymentServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BillPaymentServiceSoap {

    @WebResult(name = "paymentResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "payment", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.Payment")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.PaymentResponse")
    public id.co.sigma.mx.channel.ws.wsdl.PaymentResponse2 payment(
        @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        id.co.sigma.mx.channel.ws.wsdl.PaymentRequest request
    );

    @WebResult(name = "echoTestResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "echoTest", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.EchoTest")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/echoTest")
    @ResponseWrapper(localName = "echoTestResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.EchoTestResponse")
    public java.lang.String echoTest(
        @WebParam(name = "tx", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        java.lang.String tx
    );

    @WebResult(name = "reverseResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "reverse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.Reverse")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.ReverseResponse")
    public id.co.sigma.mx.channel.ws.wsdl.ReversalResponse reverse(
        @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        id.co.sigma.mx.channel.ws.wsdl.ReversalRequest request
    );

    @WebResult(name = "inquiryResult", targetNamespace = "bankmandiri.h2h.billpayment.ws")
    @RequestWrapper(localName = "inquiry", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.Inquiry")
    @WebMethod(action = "bankmandiri.h2h.billpayment.ws/inquiry")
    @ResponseWrapper(localName = "inquiryResponse", targetNamespace = "bankmandiri.h2h.billpayment.ws", className = "id.co.sigma.mx.channel.wsdl.InquiryResponse")
    public id.co.sigma.mx.channel.ws.wsdl.InquiryResponse2 inquiry(
        @WebParam(name = "request", targetNamespace = "bankmandiri.h2h.billpayment.ws")
        id.co.sigma.mx.channel.ws.wsdl.InquiryRequest request
    );
}
