
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package id.co.sigma.mx.channel.ws.wsdl.bri.syariah;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2017-05-13T09:57:11.842+07:00
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "BillPaymentService",
                      portName = "BillPaymentServiceSoap",
                      targetNamespace = "bri.h2h.billpayment.ws",
                      wsdlLocation = "file:/F:/KPEI/workspace8_repo/mx-channel-ws3/src/main/resources/wsdl/BillPaymentService.wsdl",
                      endpointInterface = "id.co.sigma.mx.channel.ws.wsdl.BillPaymentServiceSoap")
                      
public class BillPaymentServiceSoapImpl implements BillPaymentServiceSoap {

    private static final Logger LOG = Logger.getLogger(BillPaymentServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see id.co.sigma.mx.channel.ws.wsdl.BillPaymentServiceSoap#echoTest(java.lang.String  tx )*
     */
    public java.lang.String echoTest(java.lang.String tx) { 
        LOG.info("Executing operation echoTest");
        System.out.println(tx);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see id.co.sigma.mx.channel.ws.wsdl.BillPaymentServiceSoap#inquiry(id.co.sigma.mx.channel.ws.wsdl.InquiryRequest  request )*
     */
    public id.co.sigma.mx.channel.ws.wsdl.bri.syariah.InquiryResponse inquiry(id.co.sigma.mx.channel.ws.wsdl.bri.syariah.InquiryRequest request) { 
        LOG.info("Executing operation inquiry");
        System.out.println(request);
        try {
            id.co.sigma.mx.channel.ws.wsdl.bri.syariah.InquiryResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see id.co.sigma.mx.channel.ws.wsdl.BillPaymentServiceSoap#reverse(id.co.sigma.mx.channel.ws.wsdl.ReversalRequest  request )*
     */
    public id.co.sigma.mx.channel.ws.wsdl.bri.syariah.ReversalResponse reverse(id.co.sigma.mx.channel.ws.wsdl.bri.syariah.ReversalRequest request) { 
        LOG.info("Executing operation reverse");
        System.out.println(request);
        try {
            id.co.sigma.mx.channel.ws.wsdl.bri.syariah.ReversalResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see id.co.sigma.mx.channel.ws.wsdl.BillPaymentServiceSoap#payment(id.co.sigma.mx.channel.ws.wsdl.PaymentRequest  request )*
     */
    public id.co.sigma.mx.channel.ws.wsdl.bri.syariah.PaymentResponse payment(id.co.sigma.mx.channel.ws.wsdl.bri.syariah.PaymentRequest request) { 
        LOG.info("Executing operation payment");
        System.out.println(request);
        try {
            id.co.sigma.mx.channel.ws.wsdl.bri.syariah.PaymentResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
