package id.co.sigma.mx.channel.ws.wsdl.bri.syariah;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2017-05-13T09:57:11.855+07:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "bri.h2h.billpayment.ws", name = "BillPaymentServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BillPaymentServiceSoap {

    @WebResult(name = "echoTestResult", targetNamespace = "bri.h2h.billpayment.ws")
    @RequestWrapper(localName = "echoTest", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.EchoTest")
    @WebMethod(action = "bri.h2h.billpayment.ws/echoTest")
    @ResponseWrapper(localName = "echoTestResponse", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.EchoTestResponse")
    public java.lang.String echoTest(
        @WebParam(name = "tx", targetNamespace = "bri.h2h.billpayment.ws")
        java.lang.String tx
    );

    @WebResult(name = "inquiryResult", targetNamespace = "bri.h2h.billpayment.ws")
    @RequestWrapper(localName = "inquiry", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.Inquiry")
    @WebMethod(action = "bri.h2h.billpayment.ws/inquiry")
    @ResponseWrapper(localName = "inquiryResponse2", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.InquiryResponse2")
    public id.co.sigma.mx.channel.ws.wsdl.bri.syariah.InquiryResponse inquiry(
        @WebParam(name = "request", targetNamespace = "bri.h2h.billpayment.ws")
        id.co.sigma.mx.channel.ws.wsdl.bri.syariah.InquiryRequest request
    );

    @WebResult(name = "reverseResult", targetNamespace = "bri.h2h.billpayment.ws")
    @RequestWrapper(localName = "reverse", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.Reverse")
    @WebMethod(action = "bri.h2h.billpayment.ws/reverse")
    @ResponseWrapper(localName = "reverseResponse", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.ReverseResponse")
    public id.co.sigma.mx.channel.ws.wsdl.bri.syariah.ReversalResponse reverse(
        @WebParam(name = "request", targetNamespace = "bri.h2h.billpayment.ws")
        id.co.sigma.mx.channel.ws.wsdl.bri.syariah.ReversalRequest request
    );

    @WebResult(name = "paymentResult", targetNamespace = "bri.h2h.billpayment.ws")
    @RequestWrapper(localName = "payment", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.Payment")
    @WebMethod(action = "bri.h2h.billpayment.ws/payment")
    @ResponseWrapper(localName = "paymentResponse2", targetNamespace = "bri.h2h.billpayment.ws", className = "ws.billpayment.h2h.bri.PaymentResponse2")
    public id.co.sigma.mx.channel.ws.wsdl.bri.syariah.PaymentResponse payment(
        @WebParam(name = "request", targetNamespace = "bri.h2h.billpayment.ws")
        id.co.sigma.mx.channel.ws.wsdl.bri.syariah.PaymentRequest request
    );
}
