
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package id.co.sigma.mx.channel.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-11-20T09:03:53.940+07:00
 * Generated source version: 2.7.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "PaymentManagerControllerService",
                      portName = "PaymentManagerControllerPort",
                      targetNamespace = "urn:PaymentManagerControllerwsdl",
                      wsdlLocation = "file:/F:/testCXF/endpoint-reor01/src/main/resources/wsdl/Reor.wsdl",
                      endpointInterface = "paymentmanagercontrollerwsdl.PaymentManagerControllerPortType")
                      
public class PaymentManagerControllerPortTypeImpl implements PaymentManagerControllerPortType {

    private static final Logger LOG = Logger.getLogger(PaymentManagerControllerPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see paymentmanagercontrollerwsdl.PaymentManagerControllerPortType#reversal(paymentmanagercontrollerwsdl.ReversalRequest  req )*
     */
    public id.co.sigma.mx.channel.ws.ReversalResult reversal(id.co.sigma.mx.channel.ws.ReversalRequest req) { 
        LOG.info("Executing operation reversal");
        System.out.println(req);
        try {
            id.co.sigma.mx.channel.ws.ReversalResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see paymentmanagercontrollerwsdl.PaymentManagerControllerPortType#payment(paymentmanagercontrollerwsdl.PaymentRequest  req )*
     */
    public id.co.sigma.mx.channel.ws.PaymentResult payment(id.co.sigma.mx.channel.ws.PaymentRequest req) { 
        LOG.info("Executing operation payment");
        System.out.println(req);
        try {
            id.co.sigma.mx.channel.ws.PaymentResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see paymentmanagercontrollerwsdl.PaymentManagerControllerPortType#inquiry(paymentmanagercontrollerwsdl.InquiryRequest  req )*
     */
    public id.co.sigma.mx.channel.ws.InquiryResult inquiry(id.co.sigma.mx.channel.ws.InquiryRequest req) { 
        LOG.info("Executing operation inquiry");
        System.out.println(req);
        try {
            id.co.sigma.mx.channel.ws.InquiryResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
