package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.balicamp.model.admin.BaseAdminModel;

/**
 * MappingDetails generated by hbm2java
 * @version $Id: MappingDetails.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "mapping_details", uniqueConstraints = @UniqueConstraint(
		columnNames = { "mapping_id", "going_out", "destination" }))
public class MappingDetails extends BaseAdminModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int id;
	private Mappings mappings;
	private boolean goingOut;
	private String source;
	private String destination;

	public MappingDetails() {
	}

	public MappingDetails(int id, Mappings mappings, boolean goingOut, String source) {
		this.id = id;
		this.mappings = mappings;
		this.goingOut = goingOut;
		this.source = source;
	}

	public MappingDetails(int id, Mappings mappings, boolean goingOut, String source, String destination) {
		this.id = id;
		this.mappings = mappings;
		this.goingOut = goingOut;
		this.source = source;
		this.destination = destination;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mapping_id", nullable = false)
	public Mappings getMappings() {
		return this.mappings;
	}

	public void setMappings(Mappings mappings) {
		this.mappings = mappings;
	}

	@Column(name = "going_out", nullable = false)
	public boolean isGoingOut() {
		return this.goingOut;
	}

	public void setGoingOut(boolean goingOut) {
		this.goingOut = goingOut;
	}

	@Column(name = "source", nullable = false)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "destination", length = 100)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Override
	@Transient
	public Object getPKey() {
		return id;
	}

}
