package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MessageLogsId generated by hbm2java
 * @version $Id: MessageLogsId.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Embeddable
public class MessageLogsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String transactionId;
	private Date conversionTime;
	private String endpointCode;
	private String mappingCode;
	private boolean isRequest;
	private String raw;

	public MessageLogsId() {
	}

	public MessageLogsId(String transactionId, Date conversionTime, String endpointCode, String mappingCode,
			boolean isRequest, String raw) {
		this.transactionId = transactionId;
		this.conversionTime = conversionTime;
		this.endpointCode = endpointCode;
		this.mappingCode = mappingCode;
		this.isRequest = isRequest;
		this.raw = raw;
	}

	@Column(name = "transaction_id", nullable = false, length = 50)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "conversion_time", nullable = false, length = 29)
	public Date getConversionTime() {
		return this.conversionTime;
	}

	public void setConversionTime(Date conversionTime) {
		this.conversionTime = conversionTime;
	}

	@Column(name = "endpoint_code", nullable = false, length = 10)
	public String getEndpointCode() {
		return this.endpointCode;
	}

	public void setEndpointCode(String endpointCode) {
		this.endpointCode = endpointCode;
	}

	@Column(name = "mapping_code", nullable = false, length = 50)
	public String getMappingCode() {
		return this.mappingCode;
	}

	public void setMappingCode(String mappingCode) {
		this.mappingCode = mappingCode;
	}

	@Column(name = "is_request", nullable = false)
	public boolean isIsRequest() {
		return this.isRequest;
	}

	public void setIsRequest(boolean isRequest) {
		this.isRequest = isRequest;
	}

	@Column(name = "raw", nullable = false, length = 8192)
	public String getRaw() {
		return this.raw;
	}

	public void setRaw(String raw) {
		this.raw = raw;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessageLogsId))
			return false;
		MessageLogsId castOther = (MessageLogsId) other;

		return ((this.getTransactionId() == castOther.getTransactionId()) || (this.getTransactionId() != null
				&& castOther.getTransactionId() != null && this.getTransactionId().equals(castOther.getTransactionId())))
				&& ((this.getConversionTime() == castOther.getConversionTime()) || (this.getConversionTime() != null
						&& castOther.getConversionTime() != null && this.getConversionTime().equals(
						castOther.getConversionTime())))
				&& ((this.getEndpointCode() == castOther.getEndpointCode()) || (this.getEndpointCode() != null
						&& castOther.getEndpointCode() != null && this.getEndpointCode().equals(
						castOther.getEndpointCode())))
				&& ((this.getMappingCode() == castOther.getMappingCode()) || (this.getMappingCode() != null
						&& castOther.getMappingCode() != null && this.getMappingCode().equals(
						castOther.getMappingCode())))
				&& (this.isIsRequest() == castOther.isIsRequest())
				&& ((this.getRaw() == castOther.getRaw()) || (this.getRaw() != null && castOther.getRaw() != null && this
						.getRaw().equals(castOther.getRaw())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTransactionId() == null ? 0 : this.getTransactionId().hashCode());
		result = 37 * result + (getConversionTime() == null ? 0 : this.getConversionTime().hashCode());
		result = 37 * result + (getEndpointCode() == null ? 0 : this.getEndpointCode().hashCode());
		result = 37 * result + (getMappingCode() == null ? 0 : this.getMappingCode().hashCode());
		result = 37 * result + (this.isIsRequest() ? 1 : 0);
		result = 37 * result + (getRaw() == null ? 0 : this.getRaw().hashCode());
		return result;
	}

}
