package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Packagers generated by hbm2java
 * @version $Id: Packagers.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "packagers", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Packagers implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String code;
	private String description;
	private Set<PackagerFields> packagerFieldses = new HashSet<PackagerFields>(0);
	private Set<Mappings> mappingses = new HashSet<Mappings>(0);

	public Packagers() {
	}

	public Packagers(int id, String code) {
		this.id = id;
		this.code = code;
	}

	public Packagers(int id, String code, String description, Set<PackagerFields> packagerFieldses,
			Set<Mappings> mappingses) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.packagerFieldses = packagerFieldses;
		this.mappingses = mappingses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagers")
	public Set<PackagerFields> getPackagerFieldses() {
		return this.packagerFieldses;
	}

	public void setPackagerFieldses(Set<PackagerFields> packagerFieldses) {
		this.packagerFieldses = packagerFieldses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagers")
	public Set<Mappings> getMappingses() {
		return this.mappingses;
	}

	public void setMappingses(Set<Mappings> mappingses) {
		this.mappingses = mappingses;
	}

}
