package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PackagerFields generated by hbm2java
 * @version $Id: PackagerFields.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Entity
@Table(name = "packager_fields", uniqueConstraints = @UniqueConstraint(columnNames = { "packager_id", "field" }))
public class PackagerFields implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Packagers packagers;
	private String field;
	private int start;
	private int length;
	private boolean leftAligned;
	private String filler;
	private boolean trimmed;
	private String validRegex;
	private String description;

	public PackagerFields() {
	}

	public PackagerFields(int id, Packagers packagers, String field, int start, int length, boolean leftAligned,
			String filler, boolean trimmed) {
		this.id = id;
		this.packagers = packagers;
		this.field = field;
		this.start = start;
		this.length = length;
		this.leftAligned = leftAligned;
		this.filler = filler;
		this.trimmed = trimmed;
	}

	public PackagerFields(int id, Packagers packagers, String field, int start, int length, boolean leftAligned,
			String filler, boolean trimmed, String validRegex, String description) {
		this.id = id;
		this.packagers = packagers;
		this.field = field;
		this.start = start;
		this.length = length;
		this.leftAligned = leftAligned;
		this.filler = filler;
		this.trimmed = trimmed;
		this.validRegex = validRegex;
		this.description = description;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packager_id", nullable = false)
	public Packagers getPackagers() {
		return this.packagers;
	}

	public void setPackagers(Packagers packagers) {
		this.packagers = packagers;
	}

	@Column(name = "field", nullable = false, length = 50)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "start", nullable = false)
	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	@Column(name = "length", nullable = false)
	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	@Column(name = "left_aligned", nullable = false)
	public boolean isLeftAligned() {
		return this.leftAligned;
	}

	public void setLeftAligned(boolean leftAligned) {
		this.leftAligned = leftAligned;
	}

	@Column(name = "filler", nullable = false, length = 5)
	public String getFiller() {
		return this.filler;
	}

	public void setFiller(String filler) {
		this.filler = filler;
	}

	@Column(name = "trimmed", nullable = false)
	public boolean isTrimmed() {
		return this.trimmed;
	}

	public void setTrimmed(boolean trimmed) {
		this.trimmed = trimmed;
	}

	@Column(name = "valid_regex", length = 100)
	public String getValidRegex() {
		return this.validRegex;
	}

	public void setValidRegex(String validRegex) {
		this.validRegex = validRegex;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
