package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RcMappingsId generated by hbm2java
 * @version $Id: RcMappingsId.java 503 2013-05-24 08:13:16Z rudi.sadria $
 */
@Embeddable
public class RcMappingsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int sourceRcId;
	private int targetRcId;

	public RcMappingsId() {
	}

	public RcMappingsId(int sourceRcId, int targetRcId) {
		this.sourceRcId = sourceRcId;
		this.targetRcId = targetRcId;
	}

	@Column(name = "source_rc_id", nullable = false)
	public int getSourceRcId() {
		return this.sourceRcId;
	}

	public void setSourceRcId(int sourceRcId) {
		this.sourceRcId = sourceRcId;
	}

	@Column(name = "target_rc_id", nullable = false)
	public int getTargetRcId() {
		return this.targetRcId;
	}

	public void setTargetRcId(int targetRcId) {
		this.targetRcId = targetRcId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RcMappingsId))
			return false;
		RcMappingsId castOther = (RcMappingsId) other;

		return (this.getSourceRcId() == castOther.getSourceRcId())
				&& (this.getTargetRcId() == castOther.getTargetRcId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSourceRcId();
		result = 37 * result + this.getTargetRcId();
		return result;
	}

}
