package com.balicamp.model.mx;

// Generated Aug 11, 2014 10:05:10 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.balicamp.model.ISequencesModel;
import com.balicamp.model.admin.BaseAdminModel;
import com.balicamp.model.ui.PropertySelectionData;

/**
 * MxReport generated by hbm2java
 */
@Entity
@Table(name = "reconcile_report_weekly_log")
public class ReconcileReportWeekly extends BaseAdminModel implements ISequencesModel,
		PropertySelectionData, Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "report_id")
	private long reportID;

	@Column(name = "report_time")
	private Timestamp reportTime;

	@Column(name = "report_document")
	private String reportDocument;
	
	@Column(name = "report_type")
	private String reportType;
	
	@Column(name = "transaction_type")
	private String transactionType;
	
	@Column(name = "bank_name")
	private String bankName;
	
	@Transient
	private Integer serialNumber;

	public Integer getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(Integer serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getTransactionType() {
		return transactionType;
	}

	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}

	public ReconcileReportWeekly() {
	}
	
	public String getTransactionReportTime(){
		
		SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
		String output = formatter.format(getReportTime());
		return output;
	}

	public long getReportID() {
		return reportID;
	}

	public void setReportID(long reportID) {
		this.reportID = reportID;
	}

	public Timestamp getReportTime() {
		return reportTime;
	}

	public void setReportTime(Timestamp reportTime) {
		this.reportTime = reportTime;
	}

	public String getReportDocument() {
		return reportDocument;
	}

	public void setReportDocument(String reportDocument) {
		this.reportDocument = reportDocument;
	}
	
	public String getReportType() {
		return reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Override
	public String getPsdValue() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String getPsdLabel() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean isPsdDisabled() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public String getSequenceName() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Long getId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setId(Long id) {
		// TODO Auto-generated method stub

	}

	@Override
	public Object getPKey() {
		// TODO Auto-generated method stub
		return null;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}
	
	

}
