package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.balicamp.model.admin.BaseAdminModel;

/**
 * TransactionLogs generated by hbm2java
 */
@Entity
@Table(name = "transaction_logs", schema="public")
public class TransactionLogs extends BaseAdminModel implements java.io.Serializable,TransactionLogsBase {

	private static final long serialVersionUID = 1L;
	private TransactionLogsId id;

	public TransactionLogs() {
	}

	public TransactionLogs(TransactionLogsId id) {
		this.id = id;
	}

	@Override
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "transactionId", column = @Column(name = "transaction_id",
			nullable = false, length = 50)), @AttributeOverride(name = "transactionTime", column = @Column(
			name = "transaction_time", nullable = false, length = 29)), @AttributeOverride(name = "transactionCode",
			column = @Column(name = "transaction_code", nullable = false, length = 50)), @AttributeOverride(
			name = "mxRc", column = @Column(name = "mx_rc", nullable = false, length = 10)), @AttributeOverride(
			name = "channelCode", column = @Column(name = "channel_code", nullable = false, length = 10)), @AttributeOverride(
			name = "channelRc", column = @Column(name = "channel_rc", nullable = false, length = 10)), @AttributeOverride(
			name = "retrievalKey", column = @Column(name = "retrieval_key", nullable = false, length = 100)), @AttributeOverride(
			name = "type", column = @Column(name = "type", nullable = false, length = 20)), @AttributeOverride(
			name = "raw", column = @Column(name = "raw", nullable = false, length = 24576)) })
	public TransactionLogsId getId() {
		return this.id;
	}

	@Override
	public void setId(TransactionLogsId id) {
		this.id = id;
	}

	@Override
	@Transient
	public String getPKey() {
		return getId().getTransactionId();
	}

}
