package com.balicamp.model.mx;

// Generated Dec 13, 2012 12:58:42 PM by Hibernate Tools 3.4.0.CR1


/**
 * TransactionLogs generated by hbm2java
 */
public interface TransactionLogsBase{
	public TransactionLogsId getId();
	public void setId(TransactionLogsId id);
	public String getPKey();
}
